Repository Divyarajsinh1312/Portfolio, pull requests merged in 2022-10, with the labels that each got.

#3 Revert "Update index.html"
  index.html
Labels: hactoberfest

#4 Update index.html
  index.html
Labels: hactoberfest

#5 Update index.html
  index.html
Labels: hactoberfest, hacktoberfest-accepted

#7 Update index.html
  index.html
Labels: hactoberfest, hacktoberfest-accepted

#10 Added favicon
  README.md
  img/pro/favicon.ico
  index.html
Labels: invalid

#11 Update README.md
  README.md
Labels: hactoberfest, hacktoberfest-accepted
